### ISSUE TITLE
Should secondaryVillainAnimation be renamed to sidekickAnimation?

### ISSUE THREAD

**Issue by Norbert515** [Norbert515/flutter_villains#10]
With enough documentation, obviously.

**Comment by Solido** [comment]
JokerAnimation, SideKick are for the Hero not Villain 

> A villain's supporters are normally called henchmen, minions, or lackeys, not sidekicks.

**Comment by Norbert515** [comment]
A second poll has just started!

**Comment by hillelcoren** [comment]
> Nevertheless, some villains do have sidekicks, including Lex Luthor's Mercy Graves, the Joker's Harley Quinn...

**Comment by modulovalue** [comment]
Every villain has his evil minions. Why only be limited to two if you can have many animations?

**Comment by modulovalue** [comment]
Yes, a list for the unstoppable villain!
