### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by arsen** [Norbert515/flutter_villains#11]
After installing I get the following error when I try to build for Android. The weird thing is that for iOS it is building successfully.

```
Compiler message:
file:///Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_villains-1.1.5/lib/villains/villains.dart:383:8: Error: The method 'VillainTransitionObserver::didStartUserGesture' has fewer positional arguments than those of overridden method 'NavigatorObserver::didStartUserGesture'.
  void didStartUserGesture() {
       ^
file:///Users/user/flutter/packages/flutter/lib/src/widgets/navigator.dart:363:8: Context: This is the overridden method ('didStartUserGesture').
  void didStartUserGesture(Route<dynamic> route, Route<dynamic> previousRoute) { }
       ^
file:///Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_sequence_animation-2.0.1/lib/flutter_sequence_animation.dart:127:7: Error: The non-abstract class 'IntervalAnimatable' is missing implementations for these members:
  'transform'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

 class IntervalAnimatable<T> extends Animatable<T> {
      ^^^^^^^^^^^^^^^^^^
file:///Users/user/flutter/packages/flutter/lib/src/animation/tween.dart:39:5: Context: 'transform' is defined here.
  T transform(double t);
    ^^^^^^^^^
Compiler terminated unexpectedly.
```

**Comment by carnivash** [comment]
I'm having this same error, except that for me it works on android but fails in ios, did you manage to solve it?

**Comment by arsen** [comment]
Nope :(

**Comment by Norbert515** [comment]
I'm pretty sure this is a version problem. The villains rely on https://github.com/Norbert515/flutter_sequence_animation. The flutter framework had a breaking change with this [PR](https://github.com/flutter/flutter/pull/21540). 

Did you try updating your Flutter version?

**Comment by SnakeyHips** [comment]
Getting this as well even with the latest Flutter build `0.11.10-pre.2`. Does this mean we have to wait for this plugin to be updated before we can use it?

**Comment by carnivash** [comment]
Yes i did upgraded to newest flutter, i think that this error started to pop after the upgrade. Should we wait for a new Villains version?

**Comment by Norbert515** [comment]
Check out the newest version. It should be fixed. Let me know if it works now.

**Comment by arsen** [comment]
@Norbert515 , it is working.
Thanks for the fix.
