### ISSUE TITLE
Feature Request: N VillainAnimations

### ISSUE THREAD

**Issue by modulovalue** [Norbert515/flutter_villains#7]
it would be nice if there were a way to provide more than 2 villainAnimations 
e.g. by providing a list of VillainAnimations to a Villain or a way to combine a list of VillainAnimations to one VillainAnimation

**Comment by Norbert515** [comment]
This is certainly possible. One `Villain` takes two `VillainAnimations`, this is because usually, you don't need more. If however, you do need more, just wrap them in each other.
