### ISSUE TITLE
Villians Animation doesn't work with FutureBuilder

### ISSUE THREAD

**Issue by shtengel** [Norbert515/flutter_villains#9]
When im using a FutureBuilder and Villian inside the Widget that returns after an async function,
the Widget never shown and the animation does not start.

i tried using VillianController to invoke the animation myself but i can't use it inside the build method where my code is called after the async function finishes because it throws exception

**Comment by Norbert515** [comment]
I think my last commit (from 2 days ago) should have fixed this. Let me know if the issue still remains
